version: "3"

services:
    mysql:
        container_name: dock-stack-mysql
        image: mysql
        # restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql

    phpmyadmin:
        container_name: dock-stack-phpmyadmin
        image: phpmyadmin/phpmyadmin
        # restart: always
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_PASSWORD}
            
        depends_on:
            - mysql

volumes:
    mysql-data:

