version: "3"

services:
    postgres:
        container_name: dock-stack-postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data

    pgadmin:
        container_name: dock-stack-pgadmin
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8080:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        depends_on:
            - postgres

volumes:
    postgres-data:

