version: "3"

services:
    redis:
        container_name: dock-stack-redis
        image: redis
        # restart: always
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

    redis-commander:
        container_name: dock-stack-redis-commander
        image: rediscommander/redis-commander
        # restart: always
        ports:
            - 8083:8081
        environment:
            - REDIS_HOSTS=local:redis:6379
        depends_on:
            - redis

volumes:
    redis-data:

